乔峰读书帮

读的是书，悟的是人生。 

读好书，做好事，遇好友，过好日子: 开一片新天地

大无: 应无所住，而生其心

大有: 替往圣继绝学，为万世开太平

* 起源
最近读书似乎到了思如泉涌，取之不尽 用之不竭的地步。

不知道下笔如有神是什么境界。

只知道有很多东西可以写了，思绪无穷无尽，只是每天可写的时间不多。

读书这么快乐，为何不组建个读书会呢？

把快乐带给更多的人，是件好事。

读书有两种：

一是“应无所住，而生其心”，就是什么都不要、不想，我只是喜欢读书，读着开心，无欲无求，啥目的都没有；



一是“替天地立心，为生民立命，替往圣继绝学，为万世开太平”。



这两种，一是大无，一是大有，似乎完全不同，其实又完全相同。

怎么才能有更快乐的氛围呢？

有喜欢读书，或想“喜欢读书”的朋友加入即可。

喜欢自然就达到了一定的要求。

一种是每两天可以打一次卡，拍照、笔记、视频、音频等等均可。

一种是更自由：有朋友可能不喜欢按时打卡的压力感，那么可以选择交年费比如99元。

综上所述，成立“乔峰读书帮”，一起分享读书的快乐，创造美好的氛围。

想参与的朋友可以微信(69039958)我拉进群。

* 参与者
龙思  

刘qi  

润xin  

陈xin

kelly

豆豆爸

henry

** 分享排名

龙思

林润鑫

barret

风吹过来

梁迅

Leong

陆小米


* 已分享的书
  
how will you measure your life 

金刚经

机器学习实战hands-on

一本书读懂财报

天龙八部

国富论

西游原旨

西游记

地藏本愿经

笑傲江湖

七龙珠

郑渊洁儿童读物

管子

人生效率手册

易经受戒 - 汪曾祺

心经

地藏本愿经

笑傲江湖

七龙珠

郑渊洁儿童读物

管子

人生效率手册

易经

席慕蓉诗集

冰与火之歌 (权力的游戏)

倚天屠龙记

道德情操论

奇特的一生

大唐西域记

组合数学

黄帝内经

python cookbook

Combinatorics of finite sets

External Graph Theorem

云雀叫了一整天

* 美景
南雄银杏
* 音乐
** 雅尼
心兰相随

夜莺

河西走廊

** 急流勇退
* 美剧
权力的游戏

* 电影
一手三把刀

刀/断刀客

* 简介

龙思
第13天
最近看的书: 机器学习实战、金刚经、天龙八部
接下来想看的书:Dive into Deep Learning、金瓶梅
