* 公益“悟空图书馆”——好书之《金刚经》
小时候以为不读书不足以了解人生。
后来才明白不经历人生风雨，有的书是读不懂的。
比如<<金刚经>>
** 一切有为法，如梦幻泡影，如露亦如电，应作如是观
司马懿、司马师、司马懿做的事情都是有为法，如梦幻泡影。
刘备、诸葛亮、关羽做的事是为无为法，无论成败皆受后人传诵。

** “一切贤圣，皆因无为法而有差别。”
圣贤们无为，而无不为。
他们做不同的事情，出不同的结果，各有差别。
但对后人的激励和鼓舞却无甚差别。

** “不住相布施，福德不可思量。”
什么是不住相呢？
建设“悟空图书馆”，收到全国各地四面八方寄来的图书。
昨天收到一系列传统国学经典共44册。
有南师南怀瑾的《金刚经说什么》，有《论语别裁》，《老子他说》等等。
我想虽然不知道是哪个朋友寄的，但从寄来的书看，这位朋友深明我心。

今天按快递寄件人的电话打过去咨询，想问清楚了，git里记录下捐赠人姓名。
上海经世书局的人听说那些书都是捐赠，惊讶的语气。帮查说差不多，淘宝那边不显示购买人。

找不到这位不住相布施的朋友，更让我觉得应该把悟空图书馆做得更好, 把收到的布施更多地布施出去。


* 育儿-玩足球，学英语.

** 足球
我喜欢踢球。
在儿子未满一岁时就给他买了颜色丰富的小球他玩，那时他喜欢抱着。
长大一点，可以跑了，儿子好像对足球不怎么感冒。
我踢给他，他不接，跑去玩其他了。
我有点失望，随即想这个要随缘，爱好不能强加于人。

再打点，两岁多了。
我在家里玩球时，儿子经常跑来抢球，然后扔到其他地方，或者藏起来。喊着"我的球，我的球"。对足球的玩闹从抢球开始。
我慢慢引导儿子，告诉他张开腿站着，我把球踢得传过他双腿，就是我赢了，否则就是他赢了。
儿子一下就明白，玩得很高兴，经常笑着大声喊"我赢了，我赢了！"。
儿子也喜欢让我站着开门，他踢，一样喊"我赢了，我赢了。"

第一次带他去球场时，是周六晚上，球友们打比赛。儿子没人带，我就大胆地带儿子过去了。
一到球场，儿子埋怨地说:"爸爸你天天踢球。"
拜托，我是第一次带你来好不好。而且一周也就踢一次，顶多两次。

看来儿子不喜欢我踢球。
幸好场边有两个美女观战，帮忙逗儿子玩。
轮到我上场了，我一上去，儿子就哇哇大哭:"爸爸你下来，爸爸你不要踢"。边哭边跺脚。
我只好喊着"爸爸在这，爸爸在这。你和姐姐好好玩。" 然后继续踢。

有姐姐和球友叔叔一起哄，儿子也很快适应了。
去了三次，就一次哭太厉害让我没玩到，其他两次都玩到顺利。

我不上场，和儿子在旁边玩，他就很开心: 追着球边踢边跑，蹦蹦跳跳，偶尔拿球砸姐姐砸叔叔。踢起球来也有点模样了。
一次单位踢完聚会喝酒，也带上了儿子，大吃大喝玩到11点，儿子才闹着要回家。

** 英语
有意识地在家里说英文。
有次儿子爬高，我自然一声:"Be careful!" 儿子对一句:"别担心。"
我意识到儿子掌握得比我们意料的好。就更上心和他说英语。
打车完让他说"Thank you, uncle"。
和哥哥姐姐有打闹，说"Sorry, Brother", "Sorry, Sister"。

要我帮忙，他就说:"Daddy, Help me"。
做了错事, "Sorry, Daddy"。

有时让他多说一次，他就拒绝，说:"已经Sorry过啦"，或者"已经Thank you啦"。
"Be careful"时，也会答"Don't worry"了。
我们说一次"Shut up!", 他马上理解了，下次他听见我们吵，也来一句:"Shut up!"

两岁半，有这个感觉，应该是不错的吧。

* 援助记1-不可犯淫邪

你有手淫的习惯吗？
我就想问问，如何克制这个

- 我没有
- 一周2次没问题的

我撸了之后，有罪恶感

- 正常生理习惯，没事的

并且身体会感觉很累

- 90%的人会手淫
- 你多久一次？

我属于很疯狂的那种
最开始的时候一天三次
后来一天一次

- ...

最后发现身体不行了，就开始戒

- 2天一次就不会那么累了

今年撸了三次
搞得我整个人都不行了

-今年？ 还是今天？

今年
我不知道该怎么办了
老看黄

- 你今年才3次，也有罪恶感？

是啊
而且感觉身体很累

- 也是奇怪。你是不是一次很久？

几秒。一两分钟。

- 估计心理作用

是我以前撸的太多。后遗症。

- 色即是空。

  
---------------
找了信基督的朋友探讨了一下:
圣经中的十诫，不是一般性认为的要严守的清规戒律。
十诫解读的两个向度：国家的法律与属神的见证。
十诫里面包含神的三个性情特征，圣洁，公义与慈爱，遵行十诫就是彰显神，在地上代表神。
不可犯奸淫，触犯了，表示违背了神的公义，亏欠了配偶。同时，不犯是消极的，积极是夫妻相爱相敬，和睦合一，以致这个人这个家合乎神的心意，显明神的公义。

- 同居不玩自然是不算犯戒的?

也不好，教会有责任有权柄禁止

- 那么适当手淫呢？

是犯罪

- 。。。

---------------
又去搜了下"佛法 淫邪"。找到下面的:

为什么佛教反对手淫说它是邪淫却又不反对夫妻性生活？ - Handsome轻心的回答 - 知乎
https://www.zhihu.com/question/62506986/answer/199588633
问：为什么佛教反对手淫？
答：佛法没有反对自慰。

问：为什么佛教说自慰是邪淫？
答：佛法没有说自慰是邪淫。

问：为什么佛教又不反对夫妻性生活？
答：佛法没有反对夫妻性生活。

问：网上的佛教说手淫这不好那不好？
答：佛法没有说自慰是好或不好。

问：夫妻性生活算邪淫吗？
答：不算。

问：佛教为什么他们不反对夫妻性生活？
答：佛法所指的邪淫，只是指被谴责的性活动

这个回答我喜欢。

* 要不是腾讯不自信, TikTok可能生于腾讯

** 当年如果微信不封杀抖音，或许TikTok可以生于腾讯
2018年微信封杀抖音，禁止抖音短视频直接转发微信朋友圈。
生存是第一法则，当时觉得微信这样做无可厚非。
最近也查到抖音个人资料上，根本不允许填任何微信个人号、公众号相关的介绍。
看来腾讯、字节都是正常的商业行为，赚钱、活命要紧，其他管不了。

这让我想起当年QQ和MSN生死激战，微软怎么没像腾讯、字节一样，在操作系统里封杀QQ?
这让我对微软心生敬意。
再往前，是IE和Netscape的大战，当时微软捆绑推广IE，也被业界骂个半死。

海纳百川有容乃大。
腾讯、抖音都不是海，只是先顾自己赚钱和生存，就怕自己干涸了的湖泊。

字节和腾讯打架，就如孙悟空和二郎神打架。
要是啥时候出来个佛祖，五指一伸，说: 悟空，随便你怎么翻筋斗，怎么折腾，耍赖撒尿都行。
要是有这样的公司，那才算伟大: 与天下同利者，天下共助之。
只是这样的公司，估计不会以赚钱为第一要务了。

假若当初微信不封杀抖音，会怎么样呢？
360当年霸占了国内市场，金山的傅盛带的团队，在国内斗得头破血流也没有办法。
后来傅盛想到了海外，猎豹实现了海外突围，并成功上市。

微信不封杀抖音，马化腾张小龙可以更快看到短视频的颠覆性威力，即使打不过，也可以结合微信在海外探索的经验教训，像猎豹一样在海外突围。
说不定，就可以做出TikTok那般的成绩。

可惜腾讯还是选择了封杀。
更糟糕的是又选择让微视去对抗。
微视老早就彻底失败了，凭什么在如此强大的对手面前，赢得该有的空间?

封杀抖音，一定程度上推迟了张小龙退出视频号。
视频号之前，微信在短视频上做的功能，没几个人用。
不封杀抖音，视频号之前的失败迭代，大概率不会尝试，或者快速失败，早点进入视频号。

封不封杀抖音，都不能阻挡抖音的崛起。
不封杀，还可能逼迫腾讯内部各团队，是为“置之死地而后生”。

迟了两年，视频号终于成型了。
除快手外，抖音多了个强劲对手。

视频号日活破两亿了。
可为什么还不敢和抖音在自家的地盘，微信里正面交锋?
期待微信放开抖音的日子，那时的视频号，才是自信牛逼的视频号。


* 乔峰读书帮--地藏王:人间是地狱, 亦是天堂

乔峰读书会今天分享:
第11天: 
我不入地狱，谁入地狱。是领导力的关键考验。
今天才知道是出自<<地藏本愿经>>。

今天想，"帮"这个字好:
帮助的帮，丐帮的帮。
于是改名"乔峰读书帮"。

帮友A问: 这句啥意思呢？为啥我要入地狱？[呲牙]

帮友B说:因为地狱众生很苦，地藏王菩萨发大愿愿意自己生生世世都在地狱教化众生，渡有缘者出离地狱得以投胎再为人。

我回以<<地藏本愿经>>经的内容: 我不入地狱，谁入地狱？地狱不空，誓不成佛。众生度尽，方证菩提。

帮友A说: 所以众生的快乐是建立在地藏王的痛苦之上，虽感动却感觉不符合人性🙏

我说"各人理解不同"。
金山毒霸卖不动时，金山号召程序员们一起做市场推广，it男当然无所适从。
雷军想“我不入地狱谁入地狱”，先自己换上市场工作服去中关村卖碟。

还有一个网友理解得也很独到:
上帝把所有人都骗了，因为地狱才是最美的！佛知道真相，所以佛说：“我不入地狱，谁入地狱？”

1985年，郭广昌以史无前例的高分考入复旦大学哲学系。他至今记得，踏入大学校门那一天，哲学系学长们迎接新生的欢迎辞是——“我不入地狱，谁入地狱？”这句禅意十足的佛语充满入世情怀和献身精神，18岁的少年激动不已，豪情满怀，浑身涌动着大干一场创立基业的热血。

复旦还有个校训是：读“无用”书。
自由无用。
自由，不功利；不用，无所不用。

我问帮友B:佛陀在历史真有其人，地藏王应该也是真有其人，他/她的名字是？
佛陀在历史真有其人, 乔达摩·悉达多，不知道金庸取名乔峰是不是借用了这里的"乔"姓。
地藏王是婆罗门女，欲救母而发大愿:"地狱不空，誓不成佛; 众生度尽，方正菩提"。

我又说:
我猜测佛祖是曾经入地狱受磨难的，只是后来觉悟出了地狱。
地藏王也是入了地狱，觉悟后选择不出地狱，除非空了地狱之后。
所谓地狱，即人间的各种苦难。

帮友B说: 听一位法师说过，曾经有一世佛陀在地狱，因为要抽出筋拉车用，一愿怜悯他人，愿意自己多抽出一条拉车以减轻他人痛苦，然后就出狱了。

我: 
我佛经看得少，主要是心经、金刚经。 只是自己想来想去，感觉应该是这样。
不入地狱，去承受最深重的苦难，如何救助最广大的众生?
人间是地狱，亦是天堂。

B: 像佛陀这样样的人，世世代代都会乘愿而来的。

我: 在当下有遇到佛陀这样的人吗。

B: 有愿力就会遇上，同样的磁场就会吸引来的。
人身难得，今已得
中土难生，今已生
佛法难闻，今已闻
大道难逢，今已逢
明师难求，今生就去求吧

我: 佛即众生，众生即佛。

* 舍得
踢球是“舍，得”的上佳体验场。
如果有人喜欢一直带球，不舍，就容易导致其他人也粘球，搞得缺乏配合输球。
如果有人喜欢传球，喜欢“舍”，其他人也自然而然更多地选择传球，配合起来了就容易得胜。


好歌--急流勇退

林夕要是写成下面的意思，好友张国荣看了估计会有所感悟，会有不一样的选择


佛不是宗教吗？

-不是。佛是智慧的单字表示。教派则不同

好歌--心兰相随:
偶遇一首好歌，心兰相随的翻译也是绝了.
作者雅兰因穷困潦倒而开创斩新的音乐创作方式.
第一个能够在紫禁城开音乐会的音乐家。
难怪金庸先生说穷困潦倒有时利于达到最高境界.


当年，童话大王郑渊洁收到很多小读者的来信。
这些信多到，要用麻袋一袋一袋的装。
但是郑渊洁坚决不扔掉这些信，而是在北京买了十套房子，专门存放小读者来信。
而当年北京的房价，还是1400元一平。


欢迎来到《金瓶梅》世界！
 点击链接：https://pan.baidu.com/s/1S9CJpkQe5MuscuSvPWiFFw 
提取码：o6rv
下载：
绣像版《金瓶梅》崇祯版，格式准确，适合阅读。
或者介休版《金瓶梅》词话本的影印件。

乔峰要是更懂情趣些，阿朱就可能不会上马夫人的当，也就不会被乔峰误杀了。


“拜佛”不是弯下身体，而是放下傲慢。
“吃素”不是清口禁欲，而是心怀慈悲。
“念佛”不是积累数字，而是清净心地。
“欢喜”不是颜面和乐，而是心境舒展。
“清净”不是摒弃欲望，而是心地无私。
“布施”不是花钱买功，而是舍弃贪欲。
“信佛”不是求佛保佑，而是践行无。

前两句是和光同尘的一种解释。

和光同尘出自老子《道德经》第四章。道冲而用之或不盈，渊兮似万物之宗。挫其锐，解其纷，和其光，同其尘。湛兮似或存，吾不知谁之子，象帝之先。“和光”说的是应该让自己才能和智慧柔和下来，不露锋芒不显耀。“同”是随世的意思，即身处俗世之中不要过分的与众不同。“尘”是尘埃、垃圾的意思，指污浊的现实俗世。

* 佛法世界为什么是"黄金铺地"?
* 佛陀有段时间为什么不想讲课?
* 简单炒股
* TODO 佛法世界为什么是"黄金铺地"?
* TODO 佛陀有段时间为什么不想讲课?
* TODO 体坛神雕侠侣--莱万及其爱人
不过你要是就此认定他的妻子就是很表面看得那样娇弱，那你可就看走眼了。因为莱万自己表示，其实在家的时候自己总是被妻子压榨，就算是妻子欺负自己也不能还手，不是莱万不想还手，是他真的不敢还手。
莱万的妻子名叫安娜，如果你认为她就是一般的女子那你就错了。安娜曾经获得过职业空手道世锦赛金牌

* 欧冠半决赛
猜拜仁3:1赢
拜仁最好收一下，避免被防守反击
进球了
拜仁1:0
罗本附体
格纳布里这球真强
加上佩里西奇。两翼齐飞的罗贝里好像回来了
格纳布里好开心，莱万看着也笑了
 
* TODO 乔峰读书旅行帮--残缺胜完美, 柔弱胜刚强

昨天和群友讨论<<权力的游戏>>里的詹姆。
帮友A讨厌詹姆，正如我当初看到詹姆推下布兰时那样。

只是看完8季剧集后，绝大多数人都喜欢上了詹姆，詹姆是一个伟大的剑客，堪比拂晓神剑。
可能很多群友不看剧的不知道拂晓神剑，我就说詹姆堪比常山赵子龙，一身都是胆:
"詹姆救女骑士、单枪刺龙、孤身北上，都是帅气时刻，堪比赵子龙啊
詹姆一开始是不想那么干的，被色后逼迫了。
而且书中，是布兰掉下去瞬间，詹姆拉住了布兰。被色后骂，他只好顺势放手"

"布兰断腿，成先知；詹姆断手，成侠客。
如果你可以舍己为人，应该心无挂碍，不会焦虑的
布兰最后也没惩罚詹姆，而是和詹姆一起对抗异鬼，俩人出了出生入死的战友。
马丁好像也认同：残缺胜完美"

讨论到后面，帮友A还是说:
"赵子龙是个将军，一辈子战功无数，忠臣。有情有义有胆有谋。詹姆不配和他比"

我就猜测说A没看书，甚至可能剧集都没看完。

詹姆的错误，与其说是推布兰坠楼，更应该说，詹姆不应该和他姐姐那样。虽然可能是家族遗传。
詹姆和色后偷情，结果导致自己断手，布兰断脚。
传奇骑士詹姆武力折半都不止(可能只剩十分之一了)，布兰从小以来的骑士梦碎。

好在詹姆武力大跌后，却觉悟了统帅三军的领袖能力。
而布兰也找到了自己的使命，承担起先知的痛苦、能力和责任。

《权力的游戏》第八季第一集结尾，詹姆终于达到临冬城，看到坐在轮椅上的布兰，两人遥相对视的画面太迷幻了，这是时隔七季的对视，这是断手骑士和断腿先知的对视。

此时此刻，他俩在想什么呢？
戏精网友们给他们俩加了一段:
布兰：能推我一下吗？
詹姆：你说啥？
布兰：我说的是轮椅！


厄运，残缺，何尝不是一次机会，一次涅槃呢？
柔弱胜刚强，出自<<道德经>>。
我对上: 残缺胜完美，柔弱胜刚强。

* 对子

#接龙1
应对0821
上联：秋风浅吻园中桂
下联：

1. 北国深吟雪上梅｜刘爱强
2. 微雨洇湿陌上花/水莲
3. 春雨常润墙外花 |  王纲
4. 明月轻吟岭上梅／郑钦华
5. 慢舞轻歌雷射灯／郑
6. 冬雪深藏树上藤｜慧冬
7. 夏荷轻掩水中蛙/陌陌
8. 夏蝉轻吟岭上歌／郑钦华
9. 夏月沉浮水底天  |  吴良
10. 夜雪垂怜槛外梅/张伟
11. 骄阳似火依旧嗨//R杨军峰R
12. 落叶总归地上根/谢伟
13. 霁月清亲陌上菊(新)｜心平如镜

我:
- 慈母静观眠中娃
- 小时候，睡眼惺忪中，常看见母亲在床边慈爱地看着我，等我起床

某群友:
@龙思 
爱母欣亲坑上娃

- 坏爸笑捏怀中娃
- 苦母欣吻怀中子
//作母亲的带儿子好辛苦的

14. 慈母静观眠中娃｜龙思
15. 夏雪明呼国有冤丨随心
16. 瑞雪深拥岭上梅  丨陈太富
17. 夏雪争鸣（呼）世上冤丨随心
18. 龙思 病爷深吻照中孙
19. 龙思 坏爸笑捏怀中儿
20. 龙思 苦母欣吻怀中子

病爷笑吻照中孙  好像好一点。
我爸得了脑膜炎，老妈说，看到我儿子相片，吻个不停

21. 恶匪强劫国内民丨随心
22. 二丫电刺鬼中王 | 龙思
23. 地王慈度狱中人 | 龙思

地王，地藏王：地狱不空誓不成佛，众生度尽方证菩提

恶妻怒砸病中夫

痛儿哭慰悔中母: 我老婆发怒第一次打得儿子屁股发青，疼得哇哇叫的儿子看到妈妈哭了，忍痛爬过去安慰说:妈妈不要哭。

慧儿乐扯脚上毛  
//偷笑

#接龙1
应对0821
上联：秋风浅吻园中桂
下联：

1. 北国深吟雪上梅｜刘爱强
2. 微雨洇湿陌上花/水莲
3. 春雨常润墙外花 |  王纲
4. 明月轻吟岭上梅／郑钦华
5. 慢舞轻歌雷射灯／郑
6. 冬雪深藏树上藤｜慧冬
7. 夏荷轻掩水中蛙/陌陌
8. 夏蝉轻吟岭上歌／郑钦华
9. 夏月沉浮水底天  |  吴良
10. 夜雪垂怜槛外梅/张伟
11. 骄阳似火依旧嗨//R杨军峰R
12. 落叶总归地上根/谢伟
13. 霁月清亲陌上菊(新)｜心平如镜
14. 慈母静观眠中娃｜龙思
15. 夏雪明呼国有冤丨随心
16. 瑞雪深拥岭上梅  丨陈太富
17. 夏雪争鸣（呼）世上冤丨随心
18. 病爷笑吻照中孙 | 龙思
19. 坏爸笑捏怀中儿 | 龙思
20. 苦母欣吻怀中子 | 龙思
21. 恶匪强劫国内民丨随心
22. 二丫电刺鬼中王 | 龙思
23. 地王慈度狱中鬼 | 龙思
24. 恶妻怒砸病中夫 | 龙思
25. 慧儿乐扯父脚毛 | 龙思
26. 悲人顿悟世间道 | 龙思
27. 祖母笑逗怀中孙 | 龙思
* TODO 库鸟之凤凰在火中重生
这几年几乎全世界说库鸟废了，没人要了。利物浦夺欧冠，大家就说幸好卖了库鸟。现在库鸟圆梦欧冠，不知道之前说他的人怎么想

* TODO 莱万之神雕侠侣

* DONE 内马尔之钱太多不是好事
  
自从看到金庸先生说"世俗观念有碍参悟最高境界"，我就感觉之前有个朦胧的意念有了情绪的表示: 钱太多可能不是好事。

内马尔破纪录的天价转会巴黎圣日耳曼。
这个身价确实是对梅罗后的世界第三人的一种肯定，那如此高身价是否有坏处呢?
没多久内马尔就和卡瓦尼闹出抢点球权风波，两人像两个没长大的孩子。
真正的领袖是靠这样抢来的吗？
这样抢来的点球权，提高了进球率，却严重破坏了队内团结，两个人是自私自利的sb吗?

随后还经常看到内马尔多达二十几人的庞大陪玩团。。。
这tm是什么情况? 梅罗从没这样玩啊。

连续两三年，每到欧冠关键生死战，内马尔就伤缺。踢球的朋友都知道，疲惫状态最容易伤缺了。
为什么内马尔总是伤得那么巧? 是不是因为太有钱玩太多害的?

今年欧冠，内马尔总算没再伤，且保持了上佳竞技状态。
赛区朋友问我看好内马尔所在的巴黎圣日耳曼，还是拜仁慕尼黑。
我是中立球迷。
我想了想，想起看半决赛时内马尔那略夸张的苦瓜发型，还有耳环啥的。我就想，这装扮平时得花不少时间吧? 梅罗没这么不专注啊!
两队实力、技战术水平相差不大，起决定作用的可能是精气神以及临场细节了。
于是我猜拜仁慕尼黑2:1巴黎圣日耳曼。

看球时，我在足球群了也说:
"内马尔有两个问题，一是不够专心，花在玩乐、装扮上的时间太多了；二是拿钱太多了，不利于球队整体建设，还不如拿一半然后提升球队整体。这是我赛前猜拜仁2:1赢的原因之一"。

1:0落后，内马尔以及巴黎全队心态就明显差了，急躁了很多。
有常识的人都知道放松状态才是好状态，急躁问问状态更差。

果然巴黎错过了50周年队庆年夺冠，输给了拜仁。

内马尔又不缺钱，缺的是欧冠冠军，缺的是金球奖、世界足球先生。
不知道内马尔能否领悟有舍才有得的道理。

把费时费力的装扮去了，甚至剃个姆巴佩那样的光头。
留在巴黎，降薪，助球队整体建设，提升号召力、领袖力，明年带队夺取欧冠，就能斩获金球奖和世界足球先生。

* TODO 龟速的百度云, 微云这只兔子是不是可以醒醒?
* "夜王"对决"地藏王"
** 夜王之魔力
《权力的游戏》里异鬼的终极boss是夜王。
凡死去的人、动物、龙等被夜王寒冰手一摸，就被变成了异鬼、尸鬼、寒龙。
人类和异鬼大军的决战，死的人越多，异鬼大军就越多异鬼越是强势。
彪悍勇猛武艺高强如猎狗，都被越杀越多的异鬼打得胆战心惊，斗志殆尽，躲在角落不肯再出来。

人类军团里武功最出神入化的无面侠女二丫，一度也是被无穷无尽的异鬼围攻得满脸鲜血，只能夺路而逃，左躲右闪，陷入绝望。

夜王之强大魔力，可见一斑。

** 地藏王之神力

之前和有Top2高校老师的群里，和老师们交流诗词。
一个老师发了张图让我作"题图诗"。

我作诗如下:

婆罗门女孝母亲,
心怀慈悲度苦厄,
潜入地狱尝悲戚,
度尽众生证菩提。

婆罗门女因孝敬母亲，而发大愿"我不入地狱, 谁入地狱?"
地狱不空誓不成佛，众生度尽方证菩提。
地藏王遁入地狱，去备尝生不如死之悲苦，在极悲苦中反得大慈悲心: 为了度尽地狱中受苦的众生，宁可和众生一起受苦，众生度尽才肯成佛。

佛经记载地藏王开始是婆罗门女，其后有很多次转世，有各种相。这正如《权力的游戏》里在无面之神那学得高超本领的二丫那样，无面，也即有各种面，可以换脸变成各种人。在原著《冰与火之歌》了二丫还可以变成各种动物，这和佛经里地藏王化身动物一样。这是其一。

其二，婆罗门女为了孝敬母亲而发大愿，二丫为了替父报仇而发大愿得大本领。

其三，婆罗门女和二丫，都是女性。

** 对决
《权力的游戏》里，二丫得红神祭司梅姨指点，收敛心神，以踏雪无痕之无声身法，靠近夜王，并在夜王要击杀保存有古今人类记忆的先知"三眼乌鸦"布兰(即二丫之前的弟弟)时，从天而降以瓦雷利亚钢刀闪击夜王: 夜王和异鬼大军瞬间灰飞烟灭。

二丫即地藏王转世。
* 教育最重要的是爱心，医疗最重要的是慈悲心 
这两天，"乔峰读书旅行群"有了一位新朋友: 《奥森日记》作者黑龙老师。

教育家、百家号作者青柠的院子对《奥森日记》的评论：所有的成功都来源于那个坚持和不放弃。
不论遇到怎样的困难，无论人生陷入怎样的低潮和泥泞，只要坚持不放弃，任何人都拿你没有办法。
原北京科技大学教授曹林，从事抗肿瘤抗病毒纳米药物研究。2005年末，被确诊患有重症糖尿病，并伴有高血压症、抑郁症。
但他却没有消沉下去，而是把家搬到了北京“奥林匹克公园”附近，开启了对抗疾病的"跑步生活模式"……
14年的"跑步生活"，通过坚持不懈的努力，从上楼都困难，到能够在4小时内完成马拉松全程，并在60岁达到国家3级运动员成绩。作者不仅有效控制了血压以及被认为不治的糖尿病，重新拥有健康的生活，还治愈了抑郁症，结识了很多朋友，写出了《奥森日记》这本励志、充满人生思考和哲理的书。

说起抑郁症。看了星云大师的《释迦牟尼传》，佛陀年轻时99%是得了抑郁症。

兴趣减退，太子不想当；睡眠越来越少，食欲不振，性欲减退，啥都不想干，离家出走。按今天的医疗去医院极大概率被判抑郁症。

抑郁症其实是生理疾病，脑部的促进睡眠的垂体分泌激素过少，造成睡眠质量下降，进一步影响精神状态，产生幻觉和自杀倾向。

现代医学对抑郁症没有什么好办法，特别是西医。
哥哥张国荣也被医生判为是生理性的，然后医生又搞不定[捂脸]。
这就悲剧了。

大家看看这两张图片内容有何不同？

林夕也得过严重抑郁症。
可惜没救成功好友张国荣。

佛祖菩提树下顿悟，我猜他是找到了化解抑郁症的不药而愈的好方法，从此人类历史上出现了无私解救疾苦众生的一批人。

乔峰的姓，很可能是金庸先生取自乔达摩.悉达多，佛祖的名字。
西医救不了张国荣，佛法很大几率可以。
这些是我阅读的推测，可惜不能数学证明。要是能证明就真是太好了。@张宇森 chatc。

问题是，目前所有开药的医生，心里都没底，都是在那试。

我试着用佛法帮助相关患者，有八人说明显好转。

天龙八部后面，慕容复也得了抑郁症，还是重度。
公益“悟空图书馆”—天龙八部“王霸雄图，色即是空”
https://mp.weixin.qq.com/s/e7OY4M7CpPewkrpfMSD7iA

许巍也得过抑郁症，然后得到启发，创作了蓝莲花:
穿过幽暗的岁月，也曾感到彷徨。

所以还不如试试学习点佛法，成本极小，无副作用。
生理原因现在西医也束手无策，就是不断试。副作用无比可怕。
统计数据面前现在西医也死翘翘。

所以说这个问题目前是世界级难题，比ddos攻击还难还有意义。
特别现在新冠。

@追风筝的猪 不信佛教

今天的新闻:
世界卫生组织：全球10亿人都有精神疾病，每40秒就有1人自杀
https://3g.163.com/dy/article/FL527IM50534IP97.html

40秒一个，太可怕

@追风筝的猪:
每一秒钟都有人死去。每一秒都有人出生，谈何可怕

不知道金庸，是不是在大儿子自杀后，开始深入佛学的

教育最重要的是爱心，医疗最重要的是慈悲心。
特别是抑郁症这种。

我们这边有个初中生割腕了，她父母找我去聊了一次。

她白天黑夜刷抖音。
成绩一落千丈。
手机被他爸摔了。
然后就昼夜颠倒了。
白天睡不醒，晚上睡不着。
我说那你把你爸的手机也摔了吧。然后她就笑了下。
她爸赶紧给她买了个新手机。


蓝莲花: ”穿过幽暗的岁月，也曾感到彷徨。
天马行空的生涯，你的心了无牵挂。”
了无牵挂之后，许巍就好了。


了无牵挂，就是五蕴皆空，心无挂碍。

https://fo.ifeng.com/a/20160919/44453438_0.shtml
许巍战胜抑郁症：两位高僧是其精神领袖

https://ent.qq.com/original/bigstar/f110.html
许巍:后来说我牛的人,当年我落魄潦倒时你在哪儿呢?

我lp去了一趟西藏，带回一堆佛学相关的书。也是无心插柳。我看到书都习惯性翻翻，一翻翻出不少有意思的东西。


每个人看的感受不同。
我看着看着领悟到的是不要信任何宗教，佛教不要信，佛法也可以不信。
所谓佛法，即非佛法。
是拿来学，而不是拿来信的。

去走走挺好。 我老婆去西藏带回来的书就很好。也是旅行的一种意义。
* 安贫乐道
昨天被大伯批评不认真赚钱了。 
今天又和领导有分歧，吵了一架，算是这周破戒第一次生气。但是这个气应该是生对了。
归根结底还是要多上点心赚钱。

写文章有利于众生，短期却不利于自己赚钱。

《奇特的一生》作者柳比歇夫不喜欢赚钱，也导致家人比较痛苦。

佛祖好像离家出走后，就没去认真赚过钱了。要吃饭了，就去乞讨/化缘。

金庸小说从不讲吃的用的哪里来，古龙小说会讲武功高强的人没钱了也惨兮兮😄。

现实生活中，无论再木讷的人都会不经意间说出一些幽默风趣的话。郭大路也是一样，郭大路幽默起来，可真是笑死人。郭大路在富贵山庄经常饿肚子，肚子饿久了，看什么都像食物。有一次，王动和郭大路在富贵山庄内散步，刚下过大雪，庄园的梅花开的正盛。这时候馋嘴的郭大路开始发挥想象力了。郭大路望着院子里的白雪梅花，喃喃道："这梅花若是辣椒多好。"王动道："有什么好？"郭大路道："你看，这满地的雪岂非正像是面粉，配上几根红辣椒，岂非正好做一碗辣乎乎的热汤面。"白雪当面粉，梅花当辣椒，郭大路的想象力真的很不一般。
   --出自 古龙《欢乐英雄》

据说500年才修得同事一场的缘分，以后对错都好，还是不和同事生气了。

前天踢球，领导和我一边，看我一脚远射没打好，叫我“下去！”   
我想着这周的“莫生气”挑战，一点不生气。
说明挑战还是还有提示作用的。

末学出生贫寒的农村家庭，小时候没钱读书，书也看得少，只靠埋头苦读教科书，考个好成绩，好学校，找好工作，赚更多钱。
     明白了“道”的真义，人生的本质后，认知改变了，心念改变了。

   末学从事服务销售工作，很多名师说，会花钱的人才会赚钱，先花钱打扮自己，用些名牌，多学知识武装自己。
我的亲身经历验证了，这是错误的，都是外在表面的东西。
    学习圣贤之化后，开始做减法， 自己定目标，已经有4年，不买衣服，鞋子，不染发，不烫发，几乎不用护肤品。
  尽自己的能力去帮助需要帮助的人。
持斋吃素4年多，坚持学习圣贤文化， 随缘分享给身边需要的人。

这位朋友活得潇洒。
