* 公益“悟空图书馆”——好书之《金刚经》
小时候以为不读书不足以了解人生。
后来才明白不经历人生风雨，有的书是读不懂的。
比如<<金刚经>>
** 一切有为法，如梦幻泡影，如露亦如电，应作如是观
司马懿、司马师、司马懿做的事情都是有为法，如梦幻泡影。
刘备、诸葛亮、关羽做的事是为无为法，无论成败皆受后人传诵。

** “一切贤圣，皆因无为法而有差别。”
圣贤们无为，而无不为。
他们做不同的事情，出不同的结果，各有差别。
但对后人的激励和鼓舞却无甚差别。

** “不住相布施，福德不可思量。”
什么是不住相呢？
建设“悟空图书馆”，收到全国各地四面八方寄来的图书。
昨天收到一系列传统国学经典共44册。
有南师南怀瑾的《金刚经说什么》，有《论语别裁》，《老子他说》等等。
我想虽然不知道是哪个朋友寄的，但从寄来的书看，这位朋友深明我心。

今天按快递寄件人的电话打过去咨询，想问清楚了，git里记录下捐赠人姓名。
上海经世书局的人听说那些书都是捐赠，惊讶的语气。帮查说差不多，淘宝那边不显示购买人。

找不到这位不住相布施的朋友，更让我觉得应该把悟空图书馆做得更好, 把收到的布施更多地布施出去。

* 育儿-玩足球，学英语.

** 足球
我喜欢踢球。
在儿子未满一岁时就给他买了颜色丰富的小球他玩，那时他喜欢抱着。
长大一点，可以跑了，儿子好像对足球不怎么感冒。
我踢给他，他不接，跑去玩其他了。
我有点失望，随即想这个要随缘，爱好不能强加于人。

再打点，两岁多了。
我在家里玩球时，儿子经常跑来抢球，然后扔到其他地方，或者藏起来。喊着"我的球，我的球"。对足球的玩闹从抢球开始。
我慢慢引导儿子，告诉他张开腿站着，我把球踢得传过他双腿，就是我赢了，否则就是他赢了。
儿子一下就明白，玩得很高兴，经常笑着大声喊"我赢了，我赢了！"。
儿子也喜欢让我站着开门，他踢，一样喊"我赢了，我赢了。"

第一次带他去球场时，是周六晚上，球友们打比赛。儿子没人带，我就大胆地带儿子过去了。
一到球场，儿子埋怨地说:"爸爸你天天踢球。"
拜托，我是第一次带你来好不好。而且一周也就踢一次，顶多两次。

看来儿子不喜欢我踢球。
幸好场边有两个美女观战，帮忙逗儿子玩。
轮到我上场了，我一上去，儿子就哇哇大哭:"爸爸你下来，爸爸你不要踢"。边哭边跺脚。
我只好喊着"爸爸在这，爸爸在这。你和姐姐好好玩。" 然后继续踢。

有姐姐和球友叔叔一起哄，儿子也很快适应了。
去了三次，就一次哭太厉害让我没玩到，其他两次都玩到顺利。

我不上场，和儿子在旁边玩，他就很开心: 追着球边踢边跑，蹦蹦跳跳，偶尔拿球砸姐姐砸叔叔。踢起球来也有点模样了。
一次单位踢完聚会喝酒，也带上了儿子，大吃大喝玩到11点，儿子才闹着要回家。

** 英语
有意识地在家里说英文。
有次儿子爬高，我自然一声:"Be careful!" 儿子对一句:"别担心。"
我意识到儿子掌握得比我们意料的好。就更上心和他说英语。
打车完让他说"Thank you, uncle"。
和哥哥姐姐有打闹，说"Sorry, Brother", "Sorry, Sister"。

要我帮忙，他就说:"Daddy, Help me"。
做了错事, "Sorry, Daddy"。

有时让他多说一次，他就拒绝，说:"已经Sorry过啦"，或者"已经Thank you啦"。
"Be careful"时，也会答"Don't worry"了。
我们说一次"Shut up!", 他马上理解了，下次他听见我们吵，也来一句:"Shut up!"

两岁半，有这个感觉，应该是不错的吧。
* 佛法世界为什么是"黄金铺地"?
* 佛陀有段时间为什么不想讲课?
